In [25]:
from google.colab import drive
import numpy as np
import pandas as pd
from sklearn.neighbors import KNeighborsClassifier
from sklearn import tree
from sklearn.naive_bayes import GaussianNB
from sklearn.model_selection import cross_validate
from sklearn import metrics

# Mout Drive

In [2]:
drive.mount('/content/drive')
!ls /content/drive/MyDrive/escola/nlp

Mounted at /content/drive
hatespeech_data_clean_text.csv	hatespeech_data_tokenized.csv
hatespeech_data.csv


# Format Data

In [3]:
df = pd.read_csv('/content/drive/MyDrive/escola/nlp/hatespeech_data_tokenized.csv').to_numpy()
npdata = df[:, 1]
nptarget = df[:, -1]

In [4]:
data = []
for i in range(npdata.shape[0]):
  s = npdata[i]
  s = s[1:-1]
  l = s.split(',')
  ll = []
  for i in l:
    ll.append(int(i))
  data.append(ll)
numpy_array_for_data = np.array(data)
print("You have ", numpy_array_for_data.shape[0], "training instances tweets")
print("You have ", nptarget.shape[0], "training instances labels")
print("You have ", numpy_array_for_data.shape[1], "features")

You have  24783 training instances tweets
You have  24783 training instances labels
You have  34 features


In [11]:
updated_target = []
for i in nptarget:
  if i == 0:
    updated_target.append(1)
  else:
    updated_target.append(0)
numpy_array_for_target = np.array(updated_target)
print("You have ", numpy_array_for_target.shape[0], "training instances labels")

You have  24783 training instances labels


# Looking at data

In [23]:
from IPython.utils.text import num_ini_spaces
num_of_ones = 0
for i in numpy_array_for_target:
  if i == 1:
    num_of_ones += 1
print(1 - (num_of_ones / 24783))

0.9422991566799822


In [16]:
print(numpy_array_for_data)
print(" ")
print(numpy_array_for_target)

[[    0     0     0 ...     5    52    55]
 [    0     0     0 ...     5   552   540]
 [    0     0     0 ...  1082    75    45]
 ...
 [    0     0     0 ...   357    30   284]
 [    0     0     0 ...  1863     7  1348]
 [    0     0     0 ...   116     2 24202]]
 
[0 0 0 ... 0 0 0]


# Naive Bayes, KNN, Decision Tree

In [27]:
scoring_metrics = ['accuracy', 'precision', 'recall', 'f1']
gnb = GaussianNB()
knn = KNeighborsClassifier()
dtc = tree.DecisionTreeClassifier()


gnb_scores = cross_validate(gnb, numpy_array_for_data, numpy_array_for_target, cv=5, scoring=scoring_metrics)
knn_scores = cross_validate(knn, numpy_array_for_data, numpy_array_for_target, cv=5, scoring=scoring_metrics)
dtc_scores = cross_validate(dtc, numpy_array_for_data, numpy_array_for_target, cv=5, scoring=scoring_metrics)

print("---", "Naive Bayes Classifier", "---", '\n')
for score_name, score_value in gnb_scores.items():
    print(score_name, np.average(score_value))
print('\n')


print("---", "KNN", "---", '\n')
for score_name, score_value in knn_scores.items():
    print(score_name, np.average(score_value))
print('\n')

print("---", "Decision Tree Classifier", "---", '\n')
for score_name, score_value in dtc_scores.items():
    print(score_name, np.average(score_value))
print('\n')



--- Naive Bayes Classifier --- 

fit_time 0.018632793426513673
score_time 0.010388946533203125
test_accuracy 0.06988665070046304
test_precision 0.05761735678316684
test_recall 0.9846153846153847
test_f1 0.10886407437220522


--- KNN --- 

fit_time 0.0037104606628417967
score_time 2.411840724945068
test_accuracy 0.932817509028004
test_precision 0.024366226691808088
test_recall 0.008391608391608392
test_f1 0.012302543507362785


--- Decision Tree Classifier --- 

fit_time 0.5914178848266601
score_time 0.008699321746826172
test_accuracy 0.8815325113164498
test_precision 0.08081870130571518
test_recall 0.10209790209790208
test_f1 0.089077612797399


